### ISSUE TITLE
Iqrf daemon

### ISSUE THREAD

**Issue by openhsorg** [openhsorg/openhs#24]
Installation, setup, etc...

**Comment by openhsorg** [comment]
https://github.com/iqrfsdk/iqrf-daemon

**Comment by fmikulu** [comment]
Follow README of [https://github.com/iqrfsdk/iqrf-daemon](https://github.com/iqrfsdk/iqrf-daemon). Use build-rpi.sh and install.sh. Adapt ./configuration/IqrfInterface.json to used interface, e.g: {"IqrfInterface": "/dev/ttyACM0"}, then try to invoke ./iqrf_startup ./configuration/config.json. The same procedure would work on any Linux machine. Let me known if it works
