### ISSUE TITLE
Use logger

### ISSUE THREAD

**Issue by fmikulu** [openhsorg/openhs#35]
Please switch to logger instead of:
```java
System.out.println("annoying message");
```
Usage is easy:
```java
// initialize logger
private Logger logger = LoggerFactory.getLogger(MyClass.class);
logger.info("less annoying message");
```
Then you can switch on/off via file logback.xml

I have toubles with:
_path: floors/Floor1/doors/Door1/sensors/Lock
Door path:floors/Floor1/doors/Door1
path: floors/Floor1/doors/Door2/sensors/Lock
Door path:floors/Floor1/doors/Door2
Door path:floors/Floor1/doors/Door3
Door path:floors/Floor1/doors/Door4
Door path:floors/Floor1/doors/Door5_

**Comment by openhsorg** [comment]
Added to best practices page:  https://github.com/openhsorg/openhs/wiki/Best-Practices
