### ISSUE TITLE
Hackaton #2

### ISSUE THREAD

**Issue by MichalValny** [openhsorg/openhs#47]
Guys,
Let's come to Hackaton 2.

Successful Hackaton 1:
![img_5744](https://cloud.githubusercontent.com/assets/27553492/26236140/1d763b60-3c6f-11e7-8dbc-6ee2798a65f5.JPG)

We got a great SW and also HW progress.  This is Wemos wifi relay for home sockets:
![img_5741](https://cloud.githubusercontent.com/assets/27553492/26236208/840cf49a-3c6f-11e7-88d2-52bebed52dd7.JPG)

**Comment by MichalValny** [comment]
Terms (friday after till Saturday evening):
26. - 27.5
9. - 10.6
16.-17.6
23.-24.6

At me or Karel's place?  

Scope:
- GUI
- Prototype of Relay Sensor with Wemos and IQRF
- Prototype of Door/Window Sensor with Wemos and IQRF

**Comment by karelvalach** [comment]
I can participate 
9. - 10.6
16.-17.6

I can host this session :)
23.-24.6
